### ISSUE TITLE
Move Peers & Network Traffic sections out of Settings

### ISSUE THREAD

**Issue by yashrajd** [BitcoinDesign/Bitcoin-Core-App#88]
Currently, these sections do not include any settings at all, but just data or stats regarding the operation of the node. This could be done as a part of #58.

See screenshots below for reference:

<img width="341" alt="settings_sections" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/114083781/856595e2-ba3e-4400-85e0-66e4714b0ebf">

<img width="318" alt="peers" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/114083781/ac501918-020a-427a-a81f-e3503203cc1c">

<img width="639" alt="network traffic" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/114083781/84250433-bec4-41a2-9875-21bd58542a09">

**Comment by GBKS** [comment]
Where would you move them to? Reason they are where they are now is mostly because we just have a single button to access "other stuff" in the V1 of the application where the block clock is the primary UI and there are not tabs or other nav options. Personally, I'm fine with this living in settings.
